### ISSUE TITLE
Test OP_N

### ISSUE THREAD

**Issue by akifuj** [BitcoinCashKit/BitcoinCashKit#275]
Test `OP_N ` in `OpCodeTests.swift`

**Comment by kzumu** [comment]
@akifuj 
Hi.
Is this already implemented as below link?

https://github.com/BitcoinCashKit/BitcoinCashKit/blob/master/BitcoinCashKitTests/OpCodeTests.swift#L52

**Comment by akifuj** [comment]
Looks like yes!
You can close this issue!
