### ISSUE TITLE
Test OP_VERIFY

### ISSUE THREAD

**Issue by akifuj** [BitcoinCashKit/BitcoinCashKit#276]
Test `OP_VERIFY` in `OpCodeTests.swift`

**Comment by kzumu** [comment]
@akifuj 
Would you assign this to me?

**Comment by akifuj** [comment]
Sorry, assignees are basically for the reviewers.
If you gonna address this issue, please just add your comment.

**Comment by kzumu** [comment]
Oh, I see.
I'll implement this.

**Comment by kzumu** [comment]
@akifuj 
Sorry, this is already implemented, too.
https://github.com/BitcoinCashKit/BitcoinCashKit/blob/master/BitcoinCashKitTests/OpCodeTests.swift#L84
