### ISSUE TITLE
Test OP_DUP

### ISSUE THREAD

**Issue by akifuj** [BitcoinCashKit/BitcoinCashKit#277]
Test `OP_DUP` in `OpCodeTests.swift`

**Comment by kzumu** [comment]
@akifuj
Would you assign this to me?

**Comment by kzumu** [comment]
Sorry.
Is this already implemented?
https://github.com/BitcoinCashKit/BitcoinCashKit/blob/master/BitcoinCashKitTests/OpCodeTests.swift#L113

**Comment by akifuj** [comment]
Right! We gonna close the issue.
